[2024-06-18T21:55:52.084+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:55:52.131+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T21:55:52.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T21:55:52.141+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T21:55:52.157+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_file_formats> on 2024-06-16 00:00:00+00:00
[2024-06-18T21:55:52.166+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_schema_creation_dag', 'snowflake_create_file_formats', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/nba_schema_creation_dag.py', '--cfg-path', '/tmp/tmpkj9pgdnu']
[2024-06-18T21:55:52.169+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=34640) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:55:52.170+0000] {standard_task_runner.py:91} INFO - Job 431: Subtask snowflake_create_file_formats
[2024-06-18T21:55:52.170+0000] {standard_task_runner.py:63} INFO - Started process 34646 to run task
[2024-06-18T21:55:52.271+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:55:52.424+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_schema_creation_dag' AIRFLOW_CTX_TASK_ID='snowflake_create_file_formats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T00:00:00+00:00'
[2024-06-18T21:55:52.425+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:55:52.444+0000] {sql.py:276} INFO - Executing: 
        CREATE OR REPLACE FILE FORMAT JSON_FORMAT STRIP_OUTER_ARRAY = TRUE4 TYPE = 'JSON';
        CREATE OR REPLACE FILE FORMAT CSV_FORMAT TYPE = 'CSV' 
            SKIP_HEADER = 1 
            FIELD_DELIMITER = ',' 
            EMPTY_FIELD_AS_NULL = TRUE 
            RECORD_DELIMITER = '
'
            NULL_IF = ('NULL', 'null', '')
            FIELD_OPTIONALLY_ENCLOSED_BY = '"';
        CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT TYPE = 'PARQUET';
        
[2024-06-18T21:55:52.471+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:55:53.368+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:55:53.369+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:55:53.370+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:55:53.370+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:55:53.435+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:55:53.759+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:55:53.760+0000] {sql.py:487} INFO - Running statement: CREATE OR REPLACE FILE FORMAT JSON_FORMAT STRIP_OUTER_ARRAY = TRUE4 TYPE = 'JSON';, parameters: None
[2024-06-18T21:55:53.873+0000] {connection.py:762} INFO - closed
[2024-06-18T21:55:53.900+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:55:53.934+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:55:53.934+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001008 (22023): 01b519a3-0001-e49a-0006-023e0001a442: SQL compilation error:
invalid value [TRUE4] for parameter 'STRIP_OUTER_ARRAY'
[2024-06-18T21:55:53.959+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_schema_creation_dag, task_id=snowflake_create_file_formats, run_id=scheduled__2024-06-16T00:00:00+00:00, execution_date=20240616T000000, start_date=20240618T215552, end_date=20240618T215553
[2024-06-18T21:55:53.972+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 431 for task snowflake_create_file_formats (001008 (22023): 01b519a3-0001-e49a-0006-023e0001a442: SQL compilation error:
invalid value [TRUE4] for parameter 'STRIP_OUTER_ARRAY'; 34646)
[2024-06-18T21:55:53.994+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:55:54.036+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:55:54.044+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:59:16.069+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:59:16.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T21:59:16.128+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T21:59:16.128+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T21:59:16.143+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_file_formats> on 2024-06-16 00:00:00+00:00
[2024-06-18T21:59:16.152+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_schema_creation_dag', 'snowflake_create_file_formats', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '436', '--raw', '--subdir', 'DAGS_FOLDER/nba_schema_creation_dag.py', '--cfg-path', '/tmp/tmp5a036db7']
[2024-06-18T21:59:16.156+0000] {standard_task_runner.py:91} INFO - Job 436: Subtask snowflake_create_file_formats
[2024-06-18T21:59:16.156+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=36782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:59:16.157+0000] {standard_task_runner.py:63} INFO - Started process 36788 to run task
[2024-06-18T21:59:16.260+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:59:16.417+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_schema_creation_dag' AIRFLOW_CTX_TASK_ID='snowflake_create_file_formats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T00:00:00+00:00'
[2024-06-18T21:59:16.418+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:59:16.438+0000] {sql.py:276} INFO - Executing: 
        CREATE OR REPLACE FILE FORMAT JSON_FORMAT STRIP_OUTER_ARRAY = TRUE4 TYPE = 'JSON';
        CREATE OR REPLACE FILE FORMAT CSV_FORMAT TYPE = 'CSV' 
            SKIP_HEADER = 1 
            FIELD_DELIMITER = ',' 
            EMPTY_FIELD_AS_NULL = TRUE 
            RECORD_DELIMITER = '
'
            NULL_IF = ('NULL', 'null', '')
            FIELD_OPTIONALLY_ENCLOSED_BY = '"';
        CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT TYPE = 'PARQUET';
        
[2024-06-18T21:59:16.465+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:59:17.330+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:59:17.331+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:59:17.332+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:59:17.332+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:59:17.405+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:59:17.732+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:59:17.733+0000] {sql.py:487} INFO - Running statement: CREATE OR REPLACE FILE FORMAT JSON_FORMAT STRIP_OUTER_ARRAY = TRUE4 TYPE = 'JSON';, parameters: None
[2024-06-18T21:59:17.803+0000] {connection.py:762} INFO - closed
[2024-06-18T21:59:18.217+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:59:18.266+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:59:18.267+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001008 (22023): 01b519a7-0001-e495-0006-023e00018366: SQL compilation error:
invalid value [TRUE4] for parameter 'STRIP_OUTER_ARRAY'
[2024-06-18T21:59:18.293+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_schema_creation_dag, task_id=snowflake_create_file_formats, run_id=scheduled__2024-06-16T00:00:00+00:00, execution_date=20240616T000000, start_date=20240618T215916, end_date=20240618T215918
[2024-06-18T21:59:18.306+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 436 for task snowflake_create_file_formats (001008 (22023): 01b519a7-0001-e495-0006-023e00018366: SQL compilation error:
invalid value [TRUE4] for parameter 'STRIP_OUTER_ARRAY'; 36788)
[2024-06-18T21:59:18.347+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:59:18.390+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:59:18.395+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:38:55.205+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:38:55.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T22:38:55.264+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T22:38:55.264+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T22:38:55.278+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_file_formats> on 2024-06-16 00:00:00+00:00
[2024-06-18T22:38:55.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_schema_creation_dag', 'snowflake_create_file_formats', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '521', '--raw', '--subdir', 'DAGS_FOLDER/nba_schema_creation_dag.py', '--cfg-path', '/tmp/tmpp2m9l4ow']
[2024-06-18T22:38:55.291+0000] {standard_task_runner.py:91} INFO - Job 521: Subtask snowflake_create_file_formats
[2024-06-18T22:38:55.291+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=55507) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:38:55.292+0000] {standard_task_runner.py:63} INFO - Started process 55513 to run task
[2024-06-18T22:38:55.394+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:38:55.551+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_schema_creation_dag' AIRFLOW_CTX_TASK_ID='snowflake_create_file_formats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T00:00:00+00:00'
[2024-06-18T22:38:55.552+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:38:55.572+0000] {sql.py:276} INFO - Executing: 
        CREATE OR REPLACE FILE FORMAT JSON_FORMAT 
            STRIP_OUTER_ARRAY = TRUE
            ON_ERROR=CONTINUE 
            TYPE = 'JSON';
        CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
            TYPE = 'CSV' 
            FIELD_DELIMITER = ','
            SKIP_HEADER = 1
            NULL_IF = ('NULL', 'null')
            EMPTY_FIELD_AS_NULL = TRUE;
        CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT 
            TYPE = 'PARQUET';
        
[2024-06-18T22:38:55.600+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:38:56.445+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:38:56.446+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:38:56.447+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:38:56.447+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:38:56.512+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:38:56.786+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:38:56.786+0000] {sql.py:487} INFO - Running statement: CREATE OR REPLACE FILE FORMAT JSON_FORMAT 
            STRIP_OUTER_ARRAY = TRUE
            ON_ERROR=CONTINUE 
            TYPE = 'JSON';, parameters: None
[2024-06-18T22:38:56.893+0000] {connection.py:762} INFO - closed
[2024-06-18T22:38:56.922+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:38:56.964+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:38:56.965+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001006 (22023): 01b519ce-0001-e49a-0006-023e0001a51e: SQL compilation error:
invalid parameter 'ON_ERROR'
[2024-06-18T22:38:56.991+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_schema_creation_dag, task_id=snowflake_create_file_formats, run_id=scheduled__2024-06-16T00:00:00+00:00, execution_date=20240616T000000, start_date=20240618T223855, end_date=20240618T223856
[2024-06-18T22:38:57.005+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 521 for task snowflake_create_file_formats (001006 (22023): 01b519ce-0001-e49a-0006-023e0001a51e: SQL compilation error:
invalid parameter 'ON_ERROR'; 55513)
[2024-06-18T22:38:57.037+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:38:57.080+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:38:57.088+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:45:13.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:45:13.644+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T22:45:13.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T22:45:13.654+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T22:45:13.668+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_file_formats> on 2024-06-16 00:00:00+00:00
[2024-06-18T22:45:13.677+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_schema_creation_dag', 'snowflake_create_file_formats', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '530', '--raw', '--subdir', 'DAGS_FOLDER/nba_schema_creation_dag.py', '--cfg-path', '/tmp/tmpks38zry0']
[2024-06-18T22:45:13.681+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=58396) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:45:13.681+0000] {standard_task_runner.py:91} INFO - Job 530: Subtask snowflake_create_file_formats
[2024-06-18T22:45:13.682+0000] {standard_task_runner.py:63} INFO - Started process 58402 to run task
[2024-06-18T22:45:13.785+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:45:13.940+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_schema_creation_dag' AIRFLOW_CTX_TASK_ID='snowflake_create_file_formats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T00:00:00+00:00'
[2024-06-18T22:45:13.941+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:45:13.960+0000] {sql.py:276} INFO - Executing: 
        CREATE OR REPLACE FILE FORMAT JSON_FORMAT 
            STRIP_OUTER_ARRAY = TRUE
            ON_ERROR=CONTINUE 
            TYPE = 'JSON';
        CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
            TYPE = 'CSV' 
            FIELD_DELIMITER = ','
            SKIP_HEADER = 1
            NULL_IF = ('NULL', 'null')
            EMPTY_FIELD_AS_NULL = TRUE;
        CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT 
            TYPE = 'PARQUET';
        
[2024-06-18T22:45:13.987+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:45:14.822+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:45:14.823+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:45:14.824+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:45:14.824+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:45:14.887+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:45:15.213+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:45:15.214+0000] {sql.py:487} INFO - Running statement: CREATE OR REPLACE FILE FORMAT JSON_FORMAT 
            STRIP_OUTER_ARRAY = TRUE
            ON_ERROR=CONTINUE 
            TYPE = 'JSON';, parameters: None
[2024-06-18T22:45:15.300+0000] {connection.py:762} INFO - closed
[2024-06-18T22:45:15.327+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:45:15.363+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:45:15.364+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001006 (22023): 01b519d5-0001-e498-0006-023e0001b4ca: SQL compilation error:
invalid parameter 'ON_ERROR'
[2024-06-18T22:45:15.389+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_schema_creation_dag, task_id=snowflake_create_file_formats, run_id=scheduled__2024-06-16T00:00:00+00:00, execution_date=20240616T000000, start_date=20240618T224513, end_date=20240618T224515
[2024-06-18T22:45:15.402+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 530 for task snowflake_create_file_formats (001006 (22023): 01b519d5-0001-e498-0006-023e0001b4ca: SQL compilation error:
invalid parameter 'ON_ERROR'; 58402)
[2024-06-18T22:45:15.428+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:45:15.472+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:45:15.478+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T23:45:25.091+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T23:45:25.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T23:45:25.149+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [queued]>
[2024-06-18T23:45:25.150+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T23:45:25.163+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_create_file_formats> on 2024-06-16 00:00:00+00:00
[2024-06-18T23:45:25.175+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1793) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T23:45:25.177+0000] {standard_task_runner.py:63} INFO - Started process 1802 to run task
[2024-06-18T23:45:25.175+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_schema_creation_dag', 'snowflake_create_file_formats', 'scheduled__2024-06-16T00:00:00+00:00', '--job-id', '537', '--raw', '--subdir', 'DAGS_FOLDER/nba_schema_creation_dag.py', '--cfg-path', '/tmp/tmpe_g0un81']
[2024-06-18T23:45:25.179+0000] {standard_task_runner.py:91} INFO - Job 537: Subtask snowflake_create_file_formats
[2024-06-18T23:45:25.280+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_schema_creation_dag.snowflake_create_file_formats scheduled__2024-06-16T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T23:45:25.475+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_schema_creation_dag' AIRFLOW_CTX_TASK_ID='snowflake_create_file_formats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-16T00:00:00+00:00'
[2024-06-18T23:45:25.477+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T23:45:25.522+0000] {sql.py:276} INFO - Executing: 
        CREATE OR REPLACE FILE FORMAT JSON_FORMAT
            TYPE = 'JSON'
            STRIP_OUTER_ARRAY = TRUE;
        CREATE OR REPLACE FILE FORMAT CSV_FORMAT 
            TYPE = 'CSV' 
            FIELD_DELIMITER = ','
            SKIP_HEADER = 1
            NULL_IF = ('NULL', 'null')
            EMPTY_FIELD_AS_NULL = TRUE;
        CREATE OR REPLACE FILE FORMAT PARQUET_FORMAT 
            TYPE = 'PARQUET';
        
[2024-06-18T23:45:25.556+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:45:26.343+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:45:26.344+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T23:45:26.344+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T23:45:26.345+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:45:26.427+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:45:26.742+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T23:45:26.743+0000] {sql.py:487} INFO - Running statement: CREATE OR REPLACE FILE FORMAT JSON_FORMAT
            TYPE = 'JSON'
            STRIP_OUTER_ARRAY = TRUE;, parameters: None
[2024-06-18T23:45:28.485+0000] {connection.py:762} INFO - closed
[2024-06-18T23:45:28.513+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T23:45:28.545+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T23:45:28.546+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 090105 (22000): 01b51a11-0001-e496-0006-023e0001955e: Cannot perform CREATE FILE FORMAT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.
[2024-06-18T23:45:28.570+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_schema_creation_dag, task_id=snowflake_create_file_formats, run_id=scheduled__2024-06-16T00:00:00+00:00, execution_date=20240616T000000, start_date=20240618T234525, end_date=20240618T234528
[2024-06-18T23:45:28.588+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 537 for task snowflake_create_file_formats (090105 (22000): 01b51a11-0001-e496-0006-023e0001955e: Cannot perform CREATE FILE FORMAT. This session does not have a current database. Call 'USE DATABASE', or use a qualified name.; 1802)
[2024-06-18T23:45:28.612+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T23:45:28.652+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T23:45:28.657+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
