[2024-06-18T21:05:10.859+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:05:10.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:05:10.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:05:10.927+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T21:05:10.941+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:05:10.961+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '322', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpdh1e3q_1']
[2024-06-18T21:05:10.965+0000] {standard_task_runner.py:91} INFO - Job 322: Subtask snowflake_copy_stats
[2024-06-18T21:05:10.965+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12244) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:05:10.966+0000] {standard_task_runner.py:63} INFO - Started process 12275 to run task
[2024-06-18T21:05:11.114+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:05:11.301+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:05:11.305+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:05:11.321+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T21:05:11.354+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:05:11.619+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:05:11.624+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:05:11.624+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:05:11.625+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:05:11.706+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:05:12.818+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:05:12.819+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:05:12.877+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:05:12.877+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:05:12.878+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:05:12.878+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51971-0001-e49a-0006-023e0001a32a
[2024-06-18T21:05:12.878+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T21:05:12.958+0000] {connection.py:762} INFO - closed
[2024-06-18T21:05:12.982+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:05:13.017+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:05:13.018+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b51971-0001-e496-0006-023e0001932e: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.
[2024-06-18T21:05:13.045+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T210510, end_date=20240618T210513
[2024-06-18T21:05:13.058+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 322 for task snowflake_copy_stats (002003 (02000): 01b51971-0001-e496-0006-023e0001932e: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.; 12275)
[2024-06-18T21:05:13.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:05:13.112+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:05:13.118+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:16:38.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:16:38.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:16:38.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:16:38.791+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T21:16:38.805+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:16:38.816+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:16:38.818+0000] {standard_task_runner.py:63} INFO - Started process 19221 to run task
[2024-06-18T21:16:38.816+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '359', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp7m47suz1']
[2024-06-18T21:16:38.819+0000] {standard_task_runner.py:91} INFO - Job 359: Subtask snowflake_copy_stats
[2024-06-18T21:16:38.935+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:16:39.126+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:16:39.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:16:39.144+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T21:16:39.173+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:16:39.439+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:16:39.440+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:16:39.441+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:16:39.441+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:16:39.511+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:16:40.925+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:16:40.925+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:16:41.297+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:16:41.297+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:16:41.298+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:16:41.298+0000] {snowflake.py:410} INFO - Snowflake query id: 01b5197c-0001-e49a-0006-023e0001a3ae
[2024-06-18T21:16:41.298+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T21:16:41.656+0000] {connection.py:762} INFO - closed
[2024-06-18T21:16:41.753+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:16:41.854+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:16:41.855+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 003167 (42601): 01b5197c-0001-e365-0006-023e00016396: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake
[2024-06-18T21:16:41.881+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T211638, end_date=20240618T211641
[2024-06-18T21:16:41.894+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 359 for task snowflake_copy_stats (003167 (42601): 01b5197c-0001-e365-0006-023e00016396: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake; 19221)
[2024-06-18T21:16:41.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:16:41.965+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:16:41.967+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:21:59.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:21:59.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:21:59.897+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:21:59.898+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T21:21:59.912+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:21:59.924+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp_r6wjp0e']
[2024-06-18T21:21:59.927+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=23417) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:21:59.928+0000] {standard_task_runner.py:91} INFO - Job 391: Subtask snowflake_copy_stats
[2024-06-18T21:21:59.928+0000] {standard_task_runner.py:63} INFO - Started process 23430 to run task
[2024-06-18T21:22:00.047+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:22:00.266+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:22:00.270+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:22:00.303+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T21:22:00.337+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:22:00.618+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:22:00.621+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:22:00.621+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:22:00.622+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:22:00.688+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:22:00.942+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:22:00.942+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:22:00.989+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:22:00.989+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:22:00.990+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:22:00.991+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51982-0001-e496-0006-023e000193b6
[2024-06-18T21:22:00.991+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T21:22:02.252+0000] {connection.py:762} INFO - closed
[2024-06-18T21:22:02.280+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:22:02.330+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:22:02.331+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100038 (22018): 01b51982-0001-e49a-0006-023e0001a3e6: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
[2024-06-18T21:22:02.358+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T212159, end_date=20240618T212202
[2024-06-18T21:22:02.374+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 391 for task snowflake_copy_stats (100038 (22018): 01b51982-0001-e49a-0006-023e0001a3e6: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.; 23430)
[2024-06-18T21:22:02.405+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:22:02.442+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:22:02.444+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:47:05.684+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:47:05.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:47:05.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:47:05.740+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T21:47:05.754+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:47:05.766+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=29490) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:47:05.768+0000] {standard_task_runner.py:63} INFO - Started process 29498 to run task
[2024-06-18T21:47:05.766+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '411', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp8ofc1vel']
[2024-06-18T21:47:05.769+0000] {standard_task_runner.py:91} INFO - Job 411: Subtask snowflake_copy_stats
[2024-06-18T21:47:05.874+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:47:06.033+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:47:06.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:47:06.051+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T21:47:06.079+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:47:06.348+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:47:06.349+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:47:06.349+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:47:06.349+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:47:06.419+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:47:07.249+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:47:07.250+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:47:07.309+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:47:07.309+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:47:07.310+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:47:07.310+0000] {snowflake.py:410} INFO - Snowflake query id: 01b5199b-0001-e499-0006-023e0001c3ae
[2024-06-18T21:47:07.310+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T21:47:07.403+0000] {connection.py:762} INFO - closed
[2024-06-18T21:47:07.431+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:47:07.466+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:47:07.467+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): 01b5199b-0001-e49a-0006-023e0001a41a: SQL compilation error:
Table 'NBA_STATS.PLAYER_STATS' does not exist
[2024-06-18T21:47:07.492+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T214705, end_date=20240618T214707
[2024-06-18T21:47:07.505+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 411 for task snowflake_copy_stats (001757 (42601): 01b5199b-0001-e49a-0006-023e0001a41a: SQL compilation error:
Table 'NBA_STATS.PLAYER_STATS' does not exist; 29498)
[2024-06-18T21:47:07.515+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:47:07.549+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:47:07.551+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:49:34.378+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:49:34.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:49:34.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:49:34.434+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T21:49:34.448+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:49:34.460+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpn5u6knbx']
[2024-06-18T21:49:34.463+0000] {standard_task_runner.py:91} INFO - Job 425: Subtask snowflake_copy_stats
[2024-06-18T21:49:34.463+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=32046) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:49:34.464+0000] {standard_task_runner.py:63} INFO - Started process 32133 to run task
[2024-06-18T21:49:34.575+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:49:34.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:49:34.738+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:49:34.754+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T21:49:34.782+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:49:35.045+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:49:35.047+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:49:35.048+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:49:35.048+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:49:35.109+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:49:35.420+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:49:35.421+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:49:35.498+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:49:35.499+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:49:35.499+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:49:35.499+0000] {snowflake.py:410} INFO - Snowflake query id: 01b5199d-0001-e49c-0006-023e000173ba
[2024-06-18T21:49:35.500+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T21:49:35.570+0000] {connection.py:762} INFO - closed
[2024-06-18T21:49:35.597+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:49:35.631+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:49:35.632+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001757 (42601): 01b5199d-0001-e49c-0006-023e000173be: SQL compilation error:
Table 'NBA_STATS.PLAYER_STATS' does not exist
[2024-06-18T21:49:35.657+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T214934, end_date=20240618T214935
[2024-06-18T21:49:35.670+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 425 for task snowflake_copy_stats (001757 (42601): 01b5199d-0001-e49c-0006-023e000173be: SQL compilation error:
Table 'NBA_STATS.PLAYER_STATS' does not exist; 32133)
[2024-06-18T21:49:35.686+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:49:35.721+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:49:35.723+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:11:31.629+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:11:31.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:11:31.686+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:11:31.686+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T22:11:31.700+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T22:11:31.711+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=43731) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:11:31.713+0000] {standard_task_runner.py:63} INFO - Started process 43776 to run task
[2024-06-18T22:11:31.712+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '473', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpk9vu3m1l']
[2024-06-18T22:11:31.714+0000] {standard_task_runner.py:91} INFO - Job 473: Subtask snowflake_copy_stats
[2024-06-18T22:11:31.821+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:11:31.983+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T22:11:31.984+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:11:32.000+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T22:11:32.028+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:11:32.293+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:11:32.294+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:11:32.295+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:11:32.295+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:11:32.363+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:11:32.602+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:11:32.603+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T22:11:32.695+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:11:32.695+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T22:11:32.696+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T22:11:32.696+0000] {snowflake.py:410} INFO - Snowflake query id: 01b519b3-0001-e49d-0006-023e0001f2ee
[2024-06-18T22:11:32.696+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T22:11:34.022+0000] {connection.py:762} INFO - closed
[2024-06-18T22:11:34.046+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:11:34.095+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:11:34.096+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100038 (22018): 01b519b3-0001-e498-0006-023e0001b40a: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
[2024-06-18T22:11:34.122+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T221131, end_date=20240618T221134
[2024-06-18T22:11:34.136+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 473 for task snowflake_copy_stats (100038 (22018): 01b519b3-0001-e498-0006-023e0001b40a: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.; 43776)
[2024-06-18T22:11:34.184+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:11:34.218+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:11:34.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:20:12.866+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:20:12.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:20:12.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:20:12.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T22:20:12.938+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T22:20:12.950+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '502', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpy_gib1ee']
[2024-06-18T22:20:12.954+0000] {standard_task_runner.py:91} INFO - Job 502: Subtask snowflake_copy_stats
[2024-06-18T22:20:12.954+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=50040) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:20:12.955+0000] {standard_task_runner.py:63} INFO - Started process 50048 to run task
[2024-06-18T22:20:13.065+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:20:13.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T22:20:13.230+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:20:13.247+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T22:20:13.275+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:20:13.548+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:20:13.549+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:20:13.550+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:20:13.550+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:20:13.622+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:20:13.868+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:20:13.869+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T22:20:13.937+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:20:13.938+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T22:20:13.938+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T22:20:13.939+0000] {snowflake.py:410} INFO - Snowflake query id: 01b519bc-0001-e496-0006-023e0001949e
[2024-06-18T22:20:13.939+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T22:20:14.730+0000] {connection.py:762} INFO - closed
[2024-06-18T22:20:14.760+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:20:14.795+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:20:14.796+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 100038 (22018): 01b519bc-0001-e49c-0006-023e00017456: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.
[2024-06-18T22:20:14.821+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T222012, end_date=20240618T222014
[2024-06-18T22:20:14.834+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 502 for task snowflake_copy_stats (100038 (22018): 01b519bc-0001-e49c-0006-023e00017456: Numeric value 'PLAYER_ID' is not recognized
  File 'player_stats.csv', line 1, character 1
  Row 1, column "PLAYER_STATS"["PLAYER_ID":1]
  If you would like to continue loading when an error is encountered, use other values such as 'SKIP_FILE' or 'CONTINUE' for the ON_ERROR option. For more information on loading options, please run 'info loading_data' in a SQL client.; 50048)
[2024-06-18T22:20:14.863+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:20:14.897+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:20:14.902+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T23:48:28.109+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T23:48:28.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T23:48:28.163+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T23:48:28.163+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-18T23:48:28.177+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T23:48:28.190+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4458) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T23:48:28.187+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '553', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpormy3tfm']
[2024-06-18T23:48:28.191+0000] {standard_task_runner.py:63} INFO - Started process 4547 to run task
[2024-06-18T23:48:28.191+0000] {standard_task_runner.py:91} INFO - Job 553: Subtask snowflake_copy_stats
[2024-06-18T23:48:28.288+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T23:48:28.442+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T23:48:28.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T23:48:28.458+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS_WAREHOUSE.NBA_STATS_ANALYTICS.NBA_STATS;
        COPY INTO player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T23:48:28.484+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:48:28.736+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:48:28.737+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T23:48:28.738+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T23:48:28.738+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:48:28.813+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:48:29.082+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T23:48:29.083+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS_WAREHOUSE.NBA_STATS_ANALYTICS.NBA_STATS;, parameters: None
[2024-06-18T23:48:29.172+0000] {connection.py:762} INFO - closed
[2024-06-18T23:48:29.197+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T23:48:29.244+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T23:48:29.245+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): 01b51a14-0001-e499-0006-023e0001c526: SQL compilation error:
Object does not exist, or operation cannot be performed.
[2024-06-18T23:48:29.269+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T234828, end_date=20240618T234829
[2024-06-18T23:48:29.281+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 553 for task snowflake_copy_stats (002043 (02000): 01b51a14-0001-e499-0006-023e0001c526: SQL compilation error:
Object does not exist, or operation cannot be performed.; 4547)
[2024-06-18T23:48:29.329+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T23:48:29.362+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T23:48:29.364+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
