[2024-06-18T18:35:43.864+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:35:43.905+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:35:43.913+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:35:43.913+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T18:35:43.927+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:35:43.936+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpm3x7x_yf']
[2024-06-18T18:35:43.939+0000] {standard_task_runner.py:91} INFO - Job 199: Subtask snowflake_copy_stats
[2024-06-18T18:35:43.939+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16984) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:35:43.940+0000] {standard_task_runner.py:63} INFO - Started process 17003 to run task
[2024-06-18T18:35:44.034+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:35:44.191+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:35:44.192+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:35:44.206+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY='"');
        
[2024-06-18T18:35:44.231+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:35:44.473+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:35:44.474+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:35:44.475+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:35:44.914+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:35:44.915+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:35:44.965+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:35:44.965+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:35:44.966+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:35:44.966+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518db-0001-e49d-0006-023e0001f0ba
[2024-06-18T18:35:44.966+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (TYPE = 'CSV', FIELD_OPTIONALLY_ENCLOSED_BY='"');, parameters: None
[2024-06-18T18:35:45.530+0000] {connection.py:762} INFO - closed
[2024-06-18T18:35:45.556+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:35:45.594+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:35:45.595+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b518db-0001-e495-0006-023e0001817a: SQL compilation error:
Stage 'NBA_STATS_ANALYTICS.NBA_STATS.SNOW_S3_STAGE' does not exist or not authorized.
[2024-06-18T18:35:45.619+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T183543, end_date=20240618T183545
[2024-06-18T18:35:45.632+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 199 for task snowflake_copy_stats (002003 (02000): 01b518db-0001-e495-0006-023e0001817a: SQL compilation error:
Stage 'NBA_STATS_ANALYTICS.NBA_STATS.SNOW_S3_STAGE' does not exist or not authorized.; 17003)
[2024-06-18T18:35:45.644+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:35:45.675+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:35:45.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:46:43.686+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:46:43.769+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:46:43.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:46:43.794+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T18:46:43.832+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:46:43.852+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=20336) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:46:43.856+0000] {standard_task_runner.py:63} INFO - Started process 20418 to run task
[2024-06-18T18:46:43.856+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '217', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpi_o8i7fn']
[2024-06-18T18:46:43.862+0000] {standard_task_runner.py:91} INFO - Job 217: Subtask snowflake_copy_stats
[2024-06-18T18:46:44.073+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:46:44.369+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:46:44.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:46:44.399+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (TYPE = 'CSV');
        
[2024-06-18T18:46:44.464+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:46:44.957+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:46:44.958+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:46:44.958+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:46:45.560+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:46:45.560+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:46:45.629+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:46:45.629+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:46:45.630+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:46:45.630+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518e6-0001-e49c-0006-023e0001725a
[2024-06-18T18:46:45.630+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (TYPE = 'CSV');, parameters: None
[2024-06-18T18:46:46.001+0000] {connection.py:762} INFO - closed
[2024-06-18T18:46:46.031+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:46:46.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:46:46.099+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 003167 (42601): 01b518e6-0001-e365-0006-023e00016272: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake
[2024-06-18T18:46:46.123+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T184643, end_date=20240618T184646
[2024-06-18T18:46:46.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 217 for task snowflake_copy_stats (003167 (42601): 01b518e6-0001-e365-0006-023e00016272: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake; 20418)
[2024-06-18T18:46:46.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:46:46.197+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T18:59:35.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T18:59:35.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:59:35.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T18:59:35.537+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T18:59:35.552+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T18:59:35.565+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=25680) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T18:59:35.567+0000] {standard_task_runner.py:63} INFO - Started process 25714 to run task
[2024-06-18T18:59:35.566+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmp6gt8v4de']
[2024-06-18T18:59:35.568+0000] {standard_task_runner.py:91} INFO - Job 235: Subtask snowflake_copy_stats
[2024-06-18T18:59:35.716+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T18:59:35.930+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T18:59:35.933+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T18:59:35.947+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T18:59:35.975+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:59:36.393+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T18:59:36.397+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T18:59:36.397+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T18:59:36.921+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:59:36.923+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T18:59:36.996+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T18:59:36.997+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T18:59:36.997+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T18:59:36.997+0000] {snowflake.py:410} INFO - Snowflake query id: 01b518f3-0001-e364-0006-023e0001e14a
[2024-06-18T18:59:37.000+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T18:59:37.225+0000] {connection.py:762} INFO - closed
[2024-06-18T18:59:37.262+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T18:59:37.307+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T18:59:37.310+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 003167 (42601): 01b518f3-0001-e499-0006-023e0001c1fe: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake
[2024-06-18T18:59:37.356+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T185935, end_date=20240618T185937
[2024-06-18T18:59:37.376+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 235 for task snowflake_copy_stats (003167 (42601): 01b518f3-0001-e499-0006-023e0001c1fe: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake; 25714)
[2024-06-18T18:59:37.408+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T18:59:37.457+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T18:59:37.462+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T19:15:04.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T19:15:04.682+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:15:04.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T19:15:04.692+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T19:15:04.707+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T19:15:04.716+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpc2advnb5']
[2024-06-18T19:15:04.719+0000] {standard_task_runner.py:91} INFO - Job 256: Subtask snowflake_copy_stats
[2024-06-18T19:15:04.721+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=30871) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T19:15:04.722+0000] {standard_task_runner.py:63} INFO - Started process 30991 to run task
[2024-06-18T19:15:04.814+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T19:15:04.990+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T19:15:04.993+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T19:15:05.016+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T19:15:05.062+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:15:05.324+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T19:15:05.325+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T19:15:05.326+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T19:15:05.326+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:15:05.388+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T19:15:05.640+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:15:05.640+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T19:15:05.709+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T19:15:05.709+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T19:15:05.710+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T19:15:05.710+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51903-0001-e49d-0006-023e0001f11a
[2024-06-18T19:15:05.710+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T19:15:05.780+0000] {connection.py:762} INFO - closed
[2024-06-18T19:15:05.807+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T19:15:05.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T19:15:05.866+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b51903-0001-e49d-0006-023e0001f11e: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.
[2024-06-18T19:15:05.890+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T191504, end_date=20240618T191505
[2024-06-18T19:15:05.902+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 256 for task snowflake_copy_stats (002003 (02000): 01b51903-0001-e49d-0006-023e0001f11e: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.; 30991)
[2024-06-18T19:15:05.948+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T19:15:05.980+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T19:15:05.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T20:39:07.479+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T20:39:07.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:39:07.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T20:39:07.537+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T20:39:07.551+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_stats> on 2024-06-17 00:00:00+00:00
[2024-06-18T20:39:07.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'snowflake_copy_stats', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/nba_news_stats_etl.py', '--cfg-path', '/tmp/tmpw8fqwt0h']
[2024-06-18T20:39:07.566+0000] {standard_task_runner.py:91} INFO - Job 290: Subtask snowflake_copy_stats
[2024-06-18T20:39:07.566+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5307) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T20:39:07.567+0000] {standard_task_runner.py:63} INFO - Started process 5315 to run task
[2024-06-18T20:39:07.678+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline.snowflake_copy_stats scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T20:39:07.841+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline' AIRFLOW_CTX_TASK_ID='snowflake_copy_stats' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T20:39:07.843+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T20:39:07.859+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');
        
[2024-06-18T20:39:07.887+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:39:08.156+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T20:39:08.160+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T20:39:08.160+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T20:39:08.161+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:39:08.239+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T20:39:08.481+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:39:08.482+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T20:39:08.545+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T20:39:08.545+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T20:39:08.546+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T20:39:08.546+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51957-0001-e49c-0006-023e00017302
[2024-06-18T20:39:08.546+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.player_stats
        FROM @SNOW_S3_STAGE/player_stats.csv
        FILE_FORMAT = (FORMAT_NAME = 'CSV_FORMAT');, parameters: None
[2024-06-18T20:39:09.394+0000] {connection.py:762} INFO - closed
[2024-06-18T20:39:09.417+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T20:39:09.450+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T20:39:09.451+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 003167 (42601): 01b51957-0001-e365-0006-023e000162fe: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake
[2024-06-18T20:39:09.476+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=snowflake_copy_stats, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T203907, end_date=20240618T203909
[2024-06-18T20:39:09.490+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 290 for task snowflake_copy_stats (003167 (42601): 01b51957-0001-e365-0006-023e000162fe: Error assuming AWS_ROLE:
User: arn:aws:iam::471112850838:user/6umn0000-s is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::767397772312:role/nba_news_stats_s3_snowflake; 5315)
[2024-06-18T20:39:09.511+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T20:39:09.545+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T20:39:09.547+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
