[2024-06-18T21:09:36.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:09:36.638+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:09:36.647+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:09:36.648+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T21:09:36.671+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:09:36.722+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13974) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:09:36.728+0000] {standard_task_runner.py:63} INFO - Started process 14066 to run task
[2024-06-18T21:09:36.719+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmpskzomq6j']
[2024-06-18T21:09:36.729+0000] {standard_task_runner.py:91} INFO - Job 326: Subtask snowflake_copy_scores
[2024-06-18T21:09:37.050+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:09:37.419+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:09:37.423+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:09:37.471+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T21:09:37.541+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:09:38.075+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:09:38.076+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:09:38.077+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:09:38.077+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:09:38.145+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:09:39.009+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:09:39.011+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:09:39.088+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:09:39.088+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:09:39.089+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:09:39.089+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51975-0001-e496-0006-023e00019332
[2024-06-18T21:09:39.090+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T21:09:39.175+0000] {connection.py:762} INFO - closed
[2024-06-18T21:09:39.204+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:09:39.246+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:09:39.247+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b51975-0001-e365-0006-023e0001635a: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.
[2024-06-18T21:09:39.272+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T210936, end_date=20240618T210939
[2024-06-18T21:09:39.286+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 326 for task snowflake_copy_scores (002003 (02000): 01b51975-0001-e365-0006-023e0001635a: SQL compilation error:
Integration 'SNOW_S3' does not exist or not authorized.; 14066)
[2024-06-18T21:09:39.333+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:09:39.368+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:09:39.370+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T21:26:20.046+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T21:26:20.112+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:26:20.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T21:26:20.124+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T21:26:20.153+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T21:26:20.175+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp5sd6nk_7']
[2024-06-18T21:26:20.180+0000] {standard_task_runner.py:91} INFO - Job 393: Subtask snowflake_copy_scores
[2024-06-18T21:26:20.174+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=25178) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T21:26:20.181+0000] {standard_task_runner.py:63} INFO - Started process 25214 to run task
[2024-06-18T21:26:20.315+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T21:26:20.498+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T21:26:20.499+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T21:26:20.518+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T21:26:20.549+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:26:20.827+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T21:26:20.831+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T21:26:20.832+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T21:26:20.832+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:26:20.914+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T21:26:21.307+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:26:21.312+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T21:26:21.380+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T21:26:21.386+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T21:26:21.387+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T21:26:21.387+0000] {snowflake.py:410} INFO - Snowflake query id: 01b51986-0001-e49c-0006-023e000173a2
[2024-06-18T21:26:21.387+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T21:26:21.699+0000] {connection.py:762} INFO - closed
[2024-06-18T21:26:22.737+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T21:26:22.855+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T21:26:22.856+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b51986-0001-e495-0006-023e00018312: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T21:26:22.905+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T212620, end_date=20240618T212622
[2024-06-18T21:26:22.938+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 393 for task snowflake_copy_scores (002019 (0A000): 01b51986-0001-e495-0006-023e00018312: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 25214)
[2024-06-18T21:26:22.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T21:26:23.052+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T21:26:23.060+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:12:50.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:12:50.405+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:12:50.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:12:50.415+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T22:12:50.428+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T22:12:50.446+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=44148) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:12:50.450+0000] {standard_task_runner.py:63} INFO - Started process 44191 to run task
[2024-06-18T22:12:50.448+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '475', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp59hbqvir']
[2024-06-18T22:12:50.452+0000] {standard_task_runner.py:91} INFO - Job 475: Subtask snowflake_copy_scores
[2024-06-18T22:12:50.565+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:12:50.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T22:12:50.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:12:50.742+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T22:12:50.770+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:12:51.038+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:12:51.039+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:12:51.040+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:12:51.040+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:12:51.102+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:12:51.416+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:12:51.416+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T22:12:51.499+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:12:51.499+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T22:12:51.500+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T22:12:51.500+0000] {snowflake.py:410} INFO - Snowflake query id: 01b519b4-0001-e49d-0006-023e0001f2f2
[2024-06-18T22:12:51.500+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T22:12:51.604+0000] {connection.py:762} INFO - closed
[2024-06-18T22:12:51.629+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:12:51.662+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:12:51.663+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b519b4-0001-e498-0006-023e0001b40e: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T22:12:51.688+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T221250, end_date=20240618T221251
[2024-06-18T22:12:51.700+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 475 for task snowflake_copy_scores (002019 (0A000): 01b519b4-0001-e498-0006-023e0001b40e: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 44191)
[2024-06-18T22:12:51.717+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:12:51.751+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:12:51.753+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T22:21:32.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T22:21:32.735+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:21:32.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T22:21:32.745+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T22:21:32.760+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T22:21:32.774+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp1e1s97lw']
[2024-06-18T22:21:32.775+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=50735) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T22:21:32.779+0000] {standard_task_runner.py:91} INFO - Job 503: Subtask snowflake_copy_scores
[2024-06-18T22:21:32.779+0000] {standard_task_runner.py:63} INFO - Started process 50758 to run task
[2024-06-18T22:21:32.910+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T22:21:33.072+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T22:21:33.074+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T22:21:33.090+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS;
        COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T22:21:33.117+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:21:33.392+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T22:21:33.393+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T22:21:33.394+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T22:21:33.394+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:21:33.458+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T22:21:33.733+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:21:33.733+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS;, parameters: None
[2024-06-18T22:21:33.794+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T22:21:33.794+0000] {sql.py:496} INFO - Rows affected: 1
[2024-06-18T22:21:33.795+0000] {snowflake.py:409} INFO - Rows affected: 1
[2024-06-18T22:21:33.795+0000] {snowflake.py:410} INFO - Snowflake query id: 01b519bd-0001-e499-0006-023e0001c432
[2024-06-18T22:21:33.795+0000] {sql.py:487} INFO - Running statement: COPY INTO NBA_STATS.nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');, parameters: None
[2024-06-18T22:21:33.906+0000] {connection.py:762} INFO - closed
[2024-06-18T22:21:33.937+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T22:21:33.979+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T22:21:33.980+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002019 (0A000): 01b519bd-0001-e49d-0006-023e0001f31a: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.
[2024-06-18T22:21:34.006+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T222132, end_date=20240618T222134
[2024-06-18T22:21:34.020+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 503 for task snowflake_copy_scores (002019 (0A000): 01b519bd-0001-e49d-0006-023e0001f31a: SQL compilation error:
JSON file format can produce one and only one column of type variant, object, or array. Load data into separate columns using the MATCH_BY_COLUMN_NAME copy option or copy with transformation.; 50758)
[2024-06-18T22:21:34.043+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T22:21:34.080+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T22:21:34.082+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-18T23:49:45.005+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T23:49:45.052+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T23:49:45.062+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [queued]>
[2024-06-18T23:49:45.062+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-18T23:49:45.075+0000] {taskinstance.py:2330} INFO - Executing <Task(SQLExecuteQueryOperator): snowflake_copy_scores> on 2024-06-17 00:00:00+00:00
[2024-06-18T23:49:45.092+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline_dag', 'snowflake_copy_scores', 'scheduled__2024-06-17T00:00:00+00:00', '--job-id', '555', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline_dag.py', '--cfg-path', '/tmp/tmp38y77qwq']
[2024-06-18T23:49:45.098+0000] {standard_task_runner.py:91} INFO - Job 555: Subtask snowflake_copy_scores
[2024-06-18T23:49:45.099+0000] {logging_mixin.py:188} WARNING - /home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5279) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-18T23:49:45.100+0000] {standard_task_runner.py:63} INFO - Started process 5295 to run task
[2024-06-18T23:49:45.262+0000] {task_command.py:426} INFO - Running <TaskInstance: nba_data_pipeline_dag.snowflake_copy_scores scheduled__2024-06-17T00:00:00+00:00 [running]> on host ip-172-31-45-144.ec2.internal
[2024-06-18T23:49:45.422+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Airflow' AIRFLOW_CTX_DAG_ID='nba_data_pipeline_dag' AIRFLOW_CTX_TASK_ID='snowflake_copy_scores' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-17T00:00:00+00:00'
[2024-06-18T23:49:45.426+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T23:49:45.440+0000] {sql.py:276} INFO - Executing: 
        USE SCHEMA NBA_STATS_WAREHOUSE.NBA_STATS_ANALYTICS.NBA_STATS;
        COPY INTO nba_scores
        FROM @SNOW_S3_STAGE/nba_scores.json
        FILE_FORMAT = (FORMAT_NAME = 'JSON_FORMAT');
        
[2024-06-18T23:49:45.468+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:49:45.818+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-06-18T23:49:45.819+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.3, Platform: Linux-6.8.0-1009-aws-x86_64-with-glibc2.39
[2024-06-18T23:49:45.819+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-06-18T23:49:45.820+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:49:45.888+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-18T23:49:46.132+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-18T23:49:46.133+0000] {sql.py:487} INFO - Running statement: USE SCHEMA NBA_STATS_WAREHOUSE.NBA_STATS_ANALYTICS.NBA_STATS;, parameters: None
[2024-06-18T23:49:46.281+0000] {connection.py:762} INFO - closed
[2024-06-18T23:49:46.314+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-06-18T23:49:46.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T23:49:46.682+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 397, in run
    self._run_command(cur, sql_statement, parameters)  # type: ignore[attr-defined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/ubuntu/nba_ns_venv/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002043 (02000): 01b51a15-0001-e495-0006-023e000184b2: SQL compilation error:
Object does not exist, or operation cannot be performed.
[2024-06-18T23:49:46.706+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nba_data_pipeline_dag, task_id=snowflake_copy_scores, run_id=scheduled__2024-06-17T00:00:00+00:00, execution_date=20240617T000000, start_date=20240618T234945, end_date=20240618T234946
[2024-06-18T23:49:46.717+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 555 for task snowflake_copy_scores (002043 (02000): 01b51a15-0001-e495-0006-023e000184b2: SQL compilation error:
Object does not exist, or operation cannot be performed.; 5295)
[2024-06-18T23:49:46.730+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T23:49:46.762+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T23:49:46.763+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
